plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.5'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'org.liquibase.gradle' version '2.2.0'
}

group = 'org.example'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

 /* liquibase {
    activities {
        main {
            // Make sure this path matches your actual changelog file location
            changeLogFile 'src/main/resources/db/changelog/db.changelog-master.yaml'
            url 'jdbc:postgresql://localhost:5432/userManagement'
            username 'postgres'
            password 'ubuntu123'
            referenceUrl 'hibernate:spring:com.example.model?dialect=org.hibernate.dialect.PostgreSQLDialect'
            referenceDriver 'liquibase.ext.hibernate.database.connection.HibernateDriver'
            referenceDefaultSchemaName 'public'
        }
    }
    runList = 'main'
}

task update(type: org.liquibase.gradle.LiquibaseTask) {
    activities = ['main']
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
    liquibaseRuntime.extendsFrom runtime
}
*/

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.mapstruct:mapstruct:1.6.3'
    implementation 'org.liquibase:liquibase-core'
    compileOnly 'org.projectlombok:lombok'
    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    runtimeOnly 'org.postgresql:postgresql'
    annotationProcessor 'org.projectlombok:lombok'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.6.3'
    annotationProcessor 'org.projectlombok:lombok-mapstruct-binding:0.2.0'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    /* liquibaseRuntime(
            'org.liquibase:liquibase-core',
            'org.liquibase:liquibase-groovy-dsl:3.0.3',
            'info.picocli:picocli:4.7.5',
            'org.postgresql:postgresql',
            'org.yaml:snakeyaml:2.2',
            'org.liquibase.ext:liquibase-hibernate6:4.24.0',
            sourceSets.main.output
    )

*/
}

    tasks.named('test') {
        useJUnitPlatform()
    }
